#!/bin/bash

echo -e "\nStarting to move in... \n"
if [[ -f $HOME/.movedin ]]; then
	echo -e "Already moved in; returning\n"
	return 0
fi

echo -e "~~~ Examining host Linux distro ~~~"

TYPE=""
VERSION=""
if [[ -f /etc/redhat-release ]]; then
	echo -e "* Detected Red Hat distro *"
	TYPE="rhel"
elif [[ $(lsb_release) ]]; then
	echo -e " * Detected Ubuntu distro *"
	TYPE="ubuntu"
else
	echo -e "* Detected unkniwn distro *"
	TYPE="unknown"
fi

echo -e "\n~~~ Setting up Git ~~~\n"

GIT=$(which git)
if [[ $? -ne 0 ]]; then
	echo -e "No Git detected; install and retry"
	return 1 
fi
GITVER=$(git --version)
echo -e "Found Git, $GITVER"

echo -e "* Setting .gitconfig *"
$GIT config --global --add user.name "Michael Skelton"
$GIT config --global --add user.email "mskelton@bloomberg.net" # TO DO ~> parameterize

if [[ ! -d $HOME/Code ]]; then
	echo -e "~~~ Creating ~/Code directory ~~~"
	mkdir -p $HOME/Code/{linux,sk3l}
fi

GITHUB=https://github.com/sk3l

SRCPATH="$HOME/Code/sk3l"
echo -e "\n~~~ Pulling down source repos ~~~"

if [[ ! -d $SRCPATH/sk3lshell ]]; then
    echo -e "\n* cloning sk3lshell *"
    if ! $GIT clone -c http.sslVerify=false $GITHUB/sk3lshell $SRCPATH/sk3lshell; then
	    echo -e "Unable to clone sk3lshell; aborting"
	    return 1 
    fi
fi

if [[ ! -d $SRCPATH/tmux-conf ]]; then
    echo -e "\n* cloning tmux-conf*"
    if ! $GIT clone -c http.sslVerify=false $GITHUB/tmux-conf $SRCPATH/tmux-conf; then
	    echo -e "Unable to clone tmux-conf; aborting"
	    return 1 
    fi
fi

if [[ ! -d $SRCPATH/vim-conf ]]; then
    echo -e "\n* cloning vim-conf*"
    if ! $GIT clone -c http.sslVerify=false $GITHUB/vim-conf $SRCPATH/vim-conf; then
	    echo -e "Unable to clone vim-conf; aborting"
	    return 1 
    fi
fi

echo -e "\n~~~ Installing ViM config ~~~\n"

[[ ! -d $HOME/.vim ]] && mkdir $HOME/.vim

cp $SRCPATH/vim-conf/conf/.vimrc $HOME 
cp -R $SRCPATH/vim-conf/conf $HOME/.vim/
cp -R $SRCPATH/vim-conf/colors $HOME/.vim/

echo -e "\n~~~ Installing tmux config ~~~\n"

cp $SRCPATH/tmux-conf/.tmux.conf $HOME 

echo -e "\n~~~ Installing shell resource files ~~~\n"

cp $SRCPATH/sk3lshell/dot-files/.bashrc $HOME 

if [[ -f "$SRCPATH/sk3lshell/dot-files/.bashrc_local_$TYPE" ]]; then
    echo -e "* Found distro-specific shell resource file for $TYPE; installing *"
    cp "$SRCPATH/sk3lshell/dot-files/.bashrc_local_$TYPE" $HOME/
fi

source $HOME/.bashrc

echo $(date) > $HOME/.movedin
echo -e "\nAll moved in... \n"
